//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErpSigmaVenda.Conexao
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fornecimento
    {
        public int CodProduto { get; set; }
        public System.Guid IdFornecedores { get; set; }
        public System.Guid idProduto { get; set; }
    
        public virtual Produto Produto { get; set; }
        public virtual Fornecedores Fornecedores { get; set; }
    }
}
