//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErpSigmaVenda.Conexao
{
    using System;
    using System.Collections.Generic;
    
    public partial class Venda
    {
        public System.Guid IdVenda { get; set; }
        public System.DateTime DtVenda { get; set; }
        public decimal PreecoVenda { get; set; }
        public int QntVenda { get; set; }
        public System.Guid IdUsuario { get; set; }
        public System.Guid IdCliente { get; set; }
        public System.Guid idProduto { get; set; }
    
        public virtual Produto Produto { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Cliente Cliente { get; set; }
    }
}
